export const LOGIN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const ARTICLE = {
  FETCH_PENDING: 'FETCH_ARTICLES_PENDING',
  FETCH_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_FAIL: 'FETCH_ARTICLES_FAIL',
  CREATE_PENDING: 'CREATE_ARTICLE_PENDING',
  CREATE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_FAIL: 'CREATE_ARTICLE_FAIL',
  OPEN_DRAWER: 'OPEN_ARTICLE_DRAWER',
  CLOSE_DRAWER: 'CLOSE_ARTICLE_DRAWER',
};
