export const LOGIN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const ARTICLE = {
  FETCH_PENDING: 'FETCH_ARTICLES_PENDING',
  FETCH_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_FAIL: 'FETCH_ARTICLES_FAIL',
  CREATE_PENDING: 'CREATE_ARTICLE_PENDING',
  CREATE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_FAIL: 'CREATE_ARTICLE_FAIL',
  DELETE_PENDING: 'DELETE_ARTICLE_PENDING',
  DELETE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  DELETE_FAIL: 'DELETE_ARTICLE_FAIL',
};

export const MODAL = {
  OPEN: 'OPEN_MODAL',
  CLOSE: 'CLOSE_MODAL',
  ACCEPT: 'ACCEPT_MODAL',
  CANCEL: 'CANCEL_MODAL',
};

export const DRAWER = {
  OPEN: 'OPEN_DRAWER',
  CLOSE: 'CLOSE_DRAWER',
};
