export const LOGIN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const ARTICLE = {
  FETCH_PENDING: 'FETCH_ARTICLES_PENDING',
  FETCH_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_FAIL: 'FETCH_ARTICLES_FAIL',
};
